<a href="https://colab.research.google.com/github/avi78/Calc/blob/main/TensorflowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [3]:
scalar =tf.constant(10)

In [4]:
type(scalar)

tensorflow.python.framework.ops.EagerTensor

In [7]:
scalar.numpy()


10

In [8]:
scalar.dtype   

tf.int32

In [13]:
vectors= tf.constant([[1,2,3,4]])

In [14]:
vectors

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [17]:
print(vectors.shape)
print(vectors.dtype)   #datatype
print(vectors.numpy())

(1, 4)
<dtype: 'int32'>
[[1 2 3 4]]


In [18]:
vectors= tf.constant([[1,2,3,4],[2,4,34,45]])

In [19]:
print(vectors.shape)
print(vectors.dtype)   #datatype
print(vectors.numpy())

(2, 4)
<dtype: 'int32'>
[[ 1  2  3  4]
 [ 2  4 34 45]]


In [20]:
vectors= tf.constant([[[1,2,3,4],[2,4,34,45]],[[2,4,5,6],[4,5,6,33]]])

In [21]:
print(vectors.shape)
print(vectors.dtype)   #datatype
print(vectors.numpy())

(2, 2, 4)
<dtype: 'int32'>
[[[ 1  2  3  4]
  [ 2  4 34 45]]

 [[ 2  4  5  6]
  [ 4  5  6 33]]]


In [22]:
float_ex= tf.constant([1,2,3,4],dtype="float32")

In [23]:
float_ex.numpy()

array([1., 2., 3., 4.], dtype=float32)

# Heading 1
## Heading 2
### Heading 3
#### This is markdown language also used in github  (uk readme.md - md stands for markdown)

[Github](https://github.com)

- Tensorflow
- PyTorch
- Caffe
- Onnx

```py
print('Tensorflow')
```
```cpp
cout<<"Tensorflow"
```

*Tensorflow*

**Tensorflow**

## Zeros


In [24]:
weights= tf.zeros((3,4),dtype="float32")

In [25]:
weights.numpy()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

## Ones

In [28]:
ones_ex= tf.ones((5,3,4),dtype="float32")
ones_ex1= tf.ones((5,4,3)) # default float values
ones_ex.numpy()
ones_ex1.numpy()

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [33]:
point_one_example=tf.fill([4,5],0.1)
point_one_example.numpy()

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=int32)

## Random Tensor

In [38]:
random_ex=tf.random.uniform((3,4,5))
random_ex

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0.03665054, 0.8882917 , 0.41159427, 0.7478961 , 0.20781171],
        [0.3687253 , 0.44873333, 0.5728297 , 0.39603448, 0.97816205],
        [0.93442154, 0.9818332 , 0.40594947, 0.5146961 , 0.987378  ],
        [0.23409915, 0.5041369 , 0.13808203, 0.96708083, 0.7904279 ]],

       [[0.9779737 , 0.8401041 , 0.58616745, 0.7640431 , 0.2707101 ],
        [0.8971776 , 0.90788877, 0.00560677, 0.8653332 , 0.4959817 ],
        [0.7597438 , 0.27401412, 0.33309734, 0.9549141 , 0.37973773],
        [0.5510566 , 0.43862605, 0.9038342 , 0.87649715, 0.04582953]],

       [[0.8481941 , 0.7440734 , 0.15192938, 0.13079417, 0.71207917],
        [0.40544546, 0.06713319, 0.16324496, 0.7506423 , 0.05341542],
        [0.5075897 , 0.5906161 , 0.3583994 , 0.8753098 , 0.7320225 ],
        [0.30334723, 0.40683293, 0.9082401 , 0.7314769 , 0.17215765]]],
      dtype=float32)>

In [39]:
tf.constant? #command then question mark

## Mathematical Operations

In [47]:
a=tf.constant([1,2,3,4])
b=tf.constant([5,6,7,8])
res1=a+b  #alternative- tf.add(vector1,vector2)
res2=tf.subtract(a,b)
res3=tf.math.multiply(a,b)
res4=tf.math.divide(a,b)
print(res1)
print(res2)
print(res3)
print(res4)

tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)
tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)
tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143 0.5       ], shape=(4,), dtype=float64)


In [44]:
a=tf.random.uniform((2,3))
b=tf.random.uniform((3,2))
ans= tf.matmul(a,b)
print(ans)

tf.Tensor(
[[1.1309843  1.1265975 ]
 [0.86458135 0.8174542 ]], shape=(2, 2), dtype=float32)


In [45]:
tf.transpose(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.49802887, 0.24740672],
       [0.5910202 , 0.3058238 ],
       [0.353168  , 0.66203296]], dtype=float32)>